/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guimaraes;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.IOException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Gabriel
 */
public class GamePlayer extends javax.swing.JFrame {

    private ClientTCP client;
    
    /**
     * Creates new form GamePlayer
     */
    public GamePlayer() {
        initComponents();
        
        mapTextPane.setFont( new Font( "monospaced", Font.BOLD, 14 ) );
        
        try {
            client = new ClientTCP( mapTextPane );
        } catch ( Exception e ) {
            System.out.println( e );
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionTextField = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        mapTextPane = new javax.swing.JTextPane();
        StyledDocument doc = mapTextPane.getStyledDocument();
        SimpleAttributeSet center = new SimpleAttributeSet();
        StyleConstants.setAlignment(center, StyleConstants.ALIGN_CENTER);
        doc.setParagraphAttributes(0, doc.getLength(), center, false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                actionTextFieldKeyPressed(evt);
            }
        });

        exitButton.setText("Sair");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        mapTextPane.setEditable(false);
        jScrollPane2.setViewportView(mapTextPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addComponent(actionTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 355, Short.MAX_VALUE)
                        .addComponent(exitButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        try {
            client.exit();
        } catch ( IOException e ) {
            System.out.println( e );
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void actionTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_actionTextFieldKeyPressed
        String action = "";
            
        switch ( evt.getKeyCode() ) {
            case KeyEvent.VK_W: 
                action = "W";
                break;
            case KeyEvent.VK_A: 
                action = "A";
                break;
            case KeyEvent.VK_S: 
                action = "S";
                break;
            case KeyEvent.VK_D: 
                action = "D";
                break;
            case KeyEvent.VK_UP: 
                action = "UP";
                break;
            case KeyEvent.VK_LEFT: 
                action = "LEFT";
                break;
            case KeyEvent.VK_DOWN: 
                action = "DOWN";
                break;
            case KeyEvent.VK_RIGHT: 
                action = "RIGHT";
                break;
            case KeyEvent.VK_X: 
                action = "X";
                break;
        }

        if ( ! action.isEmpty() ) {
            actionTextField.setText( "" );
            
            client.doAction( action );
        }
    }//GEN-LAST:event_actionTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePlayer().setVisible( true );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actionTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane mapTextPane;
    // End of variables declaration//GEN-END:variables
}
