/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guimaraes;

import java.awt.Font;
import java.awt.event.KeyEvent;
import java.io.IOException;

/**
 *
 * @author Gabriel
 */
public class GamePlayer extends javax.swing.JFrame {

    private ClientTCP client;
    
    /**
     * Creates new form GamePlayer
     */
    public GamePlayer() {
        initComponents();
        
        mapTextArea.setFont( new Font( "monospaced", Font.BOLD, 14 ) );
        
        try {
            client = new ClientTCP( mapTextArea );
        } catch ( Exception e ) {
            System.out.println( e );
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionTextField = new javax.swing.JTextField();
        exitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mapTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        actionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                actionTextFieldKeyPressed(evt);
            }
        });

        exitButton.setText("Sair");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        mapTextArea.setColumns(20);
        mapTextArea.setRows(5);
        mapTextArea.setText("#######\n#     #\n#     #\n#######");
        jScrollPane1.setViewportView(mapTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(actionTextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(exitButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(actionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        try {
            client.exit();
        } catch ( IOException e ) {
            System.out.println( e );
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void actionTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_actionTextFieldKeyPressed
        String action = "";
            
        switch ( evt.getKeyCode() ) {
            case KeyEvent.VK_W: 
                action = "W";
                break;
            case KeyEvent.VK_A: 
                action = "A";
                break;
            case KeyEvent.VK_S: 
                action = "S";
                break;
            case KeyEvent.VK_D: 
                action = "D";
                break;
            case KeyEvent.VK_UP: 
                action = "UP";
                break;
            case KeyEvent.VK_LEFT: 
                action = "LEFT";
                break;
            case KeyEvent.VK_DOWN: 
                action = "DOWN";
                break;
            case KeyEvent.VK_RIGHT: 
                action = "RIGHT";
                break;
            case KeyEvent.VK_X: 
                action = "X";
                break;
        }

        if ( ! action.isEmpty() ) {
            actionTextField.setText( "" );
            
            client.doAction( action );
        }
    }//GEN-LAST:event_actionTextFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GamePlayer().setVisible( true );
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actionTextField;
    private javax.swing.JButton exitButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mapTextArea;
    // End of variables declaration//GEN-END:variables
}
